services:
  movielist:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
